// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJUdHGOkR7uvAAAP3vlJaTSQ5NscoqJTo',
    appId: '1:698749180404:web:524fa7871aa78d495101a1',
    messagingSenderId: '698749180404',
    projectId: 'banknkonde',
    authDomain: 'banknkonde.firebaseapp.com',
    databaseURL: 'https://banknkonde-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'banknkonde.appspot.com',
    measurementId: 'G-4FFSWB11K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmbKmqCBq4lWLy-qePnIor4oOEyF8JxNE',
    appId: '1:698749180404:android:33a1f97609d2f0b05101a1',
    messagingSenderId: '698749180404',
    projectId: 'banknkonde',
    databaseURL: 'https://banknkonde-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'banknkonde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0XDYN0tVrzbaIPLmsdBbdsFWUv_htqK4',
    appId: '1:698749180404:ios:36d0b9b1bfc47b685101a1',
    messagingSenderId: '698749180404',
    projectId: 'banknkonde',
    databaseURL: 'https://banknkonde-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'banknkonde.appspot.com',
    iosBundleId: 'com.example.bankNkhonde',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0XDYN0tVrzbaIPLmsdBbdsFWUv_htqK4',
    appId: '1:698749180404:ios:36d0b9b1bfc47b685101a1',
    messagingSenderId: '698749180404',
    projectId: 'banknkonde',
    databaseURL: 'https://banknkonde-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'banknkonde.appspot.com',
    iosBundleId: 'com.example.bankNkhonde',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDpQiXkxrgBlAbRvoVOnhy7467nXeUekg',
    appId: '1:698749180404:web:033d228ec9cfb6805101a1',
    messagingSenderId: '698749180404',
    projectId: 'banknkonde',
    authDomain: 'banknkonde.firebaseapp.com',
    databaseURL: 'https://banknkonde-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'banknkonde.appspot.com',
    measurementId: 'G-MV16WR43VZ',
  );

}